<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Manage Processed Data' => 'প্রক্রিয়াকৃত তথ্য ব্যবস্থাপনা',
  'Employee ID' => 'কর্মী পরিচিতি',
  'Absent' => 'অনুপস্থিত',
  'Add New Attendance' => 'নতুন উপস্থিতি তৈরী করুন',
  'Add New Leave' => 'নতুন ছুটি যোগ করুন',
  'Add to Calendar' => 'পঞ্জিকায় নিবন্ধন করুন',
  'Approved By' => 'অনুমোদনকারী ব্যক্তি',
  'Attendance Summary' => 'সংক্ষিপ্ত উপস্থিতি',
  'Break End' => 'বিরতি শেষ',
  'Break Start' => 'বিরতি শুরু',
  'Casual Leave' => 'নৈমিত্তিক ছুটি',
  'Create' => 'তৈরি করুন',
  'Daily Attendance' => 'দৈনিক উপস্থিতি',
  'Date' => 'তারিখ',
  'Date From' => 'শুরুর তারিখ',
  'Date To' => 'শেষের তারিখ',
  'Day Off' => 'বন্ধের দিন',
  'Department' => 'বিভাগ',
  'Description' => 'বিস্তারিত',
  'Duration' => 'স্থিতিকাল',
  'Early Out' => 'তাড়াতাড়ি বাহির',
  'Earn leave' => 'অর্জিত ছুটি',
  'Employee' => 'কর্মী',
  'Employee Report' => 'কর্মী প্রতিবেদন',
  'End date cannot be smaller than start date' => 'শেষের তারিখ শুরুর তারিখ থেকে ছোট হতে পারবে না।',
  'Festival Holiday' => 'উৎসব ছুটি',
  'ID' => 'পরিচিতি',
  'Image' => 'ছবি',
  'In' => 'প্রবেশ',
  'In Time' => 'প্রবেশ',
  'Json Log' => 'জেসন লগ',
  'Late In' => 'বিলম্বে প্রবেশ',
  'Leave' => 'ছুটি',
  'Leave without pay' => 'বেতনবিহীন ছুটি',
  'Manage Calendar' => 'পঞ্জিকা ব্যবস্থাপনা',
  'Manage Leaves' => 'ছুটি ব্যবস্থাপনা',
  'Manage Temporary Data' => 'অস্থায়ী উপস্থিতি ব্যবস্থাপনা',
  'Maternity leave' => 'মাতৃত্বকালীন ছুটি',
  'Mode' => 'ধরণ',
  'Note' => 'মন্তব্য',
  'Others Holiday' => 'অন্যান্য ছুটি',
  'Others leave' => 'অন্যান্য ছুটি',
  'Out' => 'বাহির',
  'Out Time' => 'শেষের সময়',
  'Over Time' => 'অতিরিক্ত সময়',
  'Prasent' => 'উপস্থিত',
  'Process Data' => 'তথ্য প্রক্রিয়াকরণ',
  'Processed' => 'প্রক্রিয়াকৃত',
  'Processed Time' => 'প্রক্রিয়ার সময়',
  'Processing...' => 'প্রক্রিয়াধীন...',
  'Responsible Person' => 'দায়িত্বপ্রাপ্ত ব্যক্তি',
  'Save' => 'সংরক্ষণ করুন',
  'Save Permanently' => 'স্থাযীভাবে সংরক্ষণ করুন',
  'Search' => 'অনুসন্ধান',
  'Shift' => 'শিফট',
  'Sick Leave' => 'অসুস্থকালীন ছুটি',
  'Status' => 'অবস্থা',
  'Successfully Created.' => 'সফলভাবে তৈরি করা হয়েছে।',
  'Successfully Updated.' => 'সফলভাবে সংরক্ষণ করা হয়েছে।',
  'Temporary Attendance: {n}' => 'অস্থায়ী উপস্থিতিঃ {n}',
  'Time' => 'সময়',
  'Title' => 'শিরোনাম',
  'Type' => 'ধরণ',
  'Unprocessed' => 'অপ্রক্রিয়াকৃত',
  'Weekly Holiday' => 'সপ্তাহিক ছুটি',
  'Work Hour' => 'কর্মঘণ্টা',
  'Workday' => 'কর্মদিবস',
  'Special Holiday'=>'বিশেষ ছুটি',
	'National Holiday'=>'জাতীয় ছুটি',
);
